name: Build and Lint

on:
  push:
  pull_requests:
    branches:
      - "*"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run : npm run build