name: Merge to Main

on:
    push:
        branches:
            - main

jobs:
    create-tag:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-versions: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Get NPM version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1
            - name: Create Tag
              uses: ncipollo/release-action@v1
              with:
                tag: ${{steps.package-version.outputs.current-version}}
                name: Release ${{steps.package-version.outputs.current-version}}